### ISSUE TITLE
ERROR: Source and destination can not be the same - followon from #2291

### ISSUE THREAD

**Issue by higgi13425** [quarto-dev/quarto-cli#10276]
### Bug description

`ERROR: Source and destination cannot be the same.`

I published interactively to quarto-pub once. 
The file `_publish.yml` was created.

Now trying to set up auto-update with linux server and cron.
Running in cron on a linux server:

`35 12 * * * /app/apps/rhel8/quarto/1.4.549/bin/quarto publish quarto-pub '/home/phiggins/data_space/shared_projects/sgm_multicenter/sgm_data.qmd' --no-prompt --no-browser >> '/home/phiggins/data_space/shared_projects/sgm_multicenter/siteupdate.log' 2>&1`

Everything renders to HTML, then I get the above error in the log.

Full details from the log:

[1m[34mRendering for publish:
[39m[22m
[31m

processing file: sgm_data.qmd
[39m1/17
2/17 [setup]
3/17
4/17 [unnamed-chunk-1]
5/17
6/17 [unnamed-chunk-2]
7/17
8/17 [unnamed-chunk-3]
9/17
10/17 [unnamed-chunk-4]
11/17
12/17 [unnamed-chunk-5]
13/17
14/17 [unnamed-chunk-6]
15/17
16/17 [unnamed-chunk-7]
17/17
[31moutput file: sgm_data.knit.md

[39m[1mpandoc [22m
to: html
output-file: sgm_data.html
standalone: true
section-divs: true
html-math-method: mathjax
wrap: none
default-image-extension: png

[1mmetadata[22m
document-css: false
link-citations: true
date-format: long
lang: en
title: SGM Data for Pfizer Multicenter Project
editor: visual

[91mERROR: Source and destination cannot be the same.

Stack trace:
at copyTo (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:41328:15)
at stageDocumentPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102128:9)
at renderForPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102116:24)
at eventLoopTick (ext:core/01_core.js:183:11)
at async handlePublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102015:26)
at async publishDocument (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106587:38)
at async publish6 (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106679:132)
at async doPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106639:13)
at async publishAction (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106650:9)
at async Command.fn (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106627:9)[39m

### Steps to reproduce

Can not share quarto doc due to PHI in source.
But as seen in the log, it renders to HTML, and interactive quarto publish works fine.
But a problem when trying to update with cron on a linux server

### Expected behavior

HTML should be published to update the website on quarto-pub

### Actual behavior

get error seen in log above

[91mERROR: Source and destination cannot be the same.

### Your environment

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.10 (Ootpa)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.8.0 
LAPACK: /usr/lib64/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] flextable_0.9.6    REDCapTidieR_1.1.1 janitor_2.2.0      here_1.0.1        
 [5] lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1      dplyr_1.1.4       
 [9] purrr_1.0.2        readr_2.1.5        tidyr_1.3.1        tibble_3.2.1      
[13] ggplot2_3.5.1      tidyverse_2.0.0   

loaded via a namespace (and not attached):
 [1] gtable_0.3.5            xfun_0.42               htmlwidgets_1.6.4      
 [4] tzdb_0.4.0              REDCapR_1.1.0           vctrs_0.6.5            
 [7] tools_4.3.2             generics_0.1.3          curl_5.2.0             
[10] fansi_1.0.6             pkgconfig_2.0.3         data.table_1.15.0      
[13] checkmate_2.3.1         uuid_1.2-0              lifecycle_1.0.4        
[16] compiler_4.3.2          textshaping_0.3.7       munsell_0.5.1          
[19] snakecase_0.11.1        httpuv_1.6.15           fontquiver_0.2.1       
[22] fontLiberation_0.1.0    htmltools_0.5.7         later_1.3.2            
[25] pillar_1.9.0            crayon_1.5.2            gfonts_0.2.0           
[28] openssl_2.1.1           mime_0.12               fontBitstreamVera_0.1.1
[31] zip_2.3.1               tidyselect_1.2.1        digest_0.6.35          
[34] formattable_0.2.1       stringi_1.8.4           rprojroot_2.0.4        
[37] fastmap_1.1.1           grid_4.3.2              colorspace_2.1-0       
[40] cli_3.6.2               magrittr_2.0.3          crul_1.4.2             
[43] utf8_1.2.4              withr_3.0.0             promises_1.3.0         
[46] gdtools_0.3.7           scales_1.3.0            backports_1.4.1        
[49] timechange_0.3.0        officer_0.6.6           rmarkdown_2.25         
[52] lobstr_1.1.2            ragg_1.2.7              askpass_1.2.0          
[55] hms_1.1.3               shiny_1.8.1.1           evaluate_0.24.0        
[58] knitr_1.45              rlang_1.1.4             Rcpp_1.0.12            
[61] xtable_1.8-4            glue_1.7.0              httpcode_0.3.0         
[64] xml2_1.3.6              rstudioapi_0.15.0       jsonlite_1.8.8         
[67] R6_2.5.1                systemfonts_1.0.5      

### Quarto check output

quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /usr/lib/rstudio-server/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.6.8
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /app/apps/rhel8/R/4.3.2/lib64/R
      LibPaths:
        - /home/phiggins/R/x86_64-pc-linux-gnu-library/4.3
        - /app/apps/rhel8/R/4.3.2/lib64/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
@higgi13425 could you upgrade your version of Quarto.
We are at 1.5 and you are using 1.3.
Many issues have been fixed since then.

**Comment by higgi13425** [comment]
Will do.

**Comment by higgi13425** [comment]
Now quarto 1.5.54.
Still getting the same error in CRON when I use paths defined by a symlink.
Looks like when I use the true path it works fine.
Thanks- looks like the symlink path was the problem & remains  a problem in 1.5

**Comment by higgi13425** [comment]
I'm afraid I learned that the hard way.
But now updating daily.
[Link to clinical trial progress website](https://phiggins.quarto.pub/smart-dashboard/)

**Comment by higgi13425** [comment]
For folks who find this in the future and want to use cron to schedule quarto doc publishing updates, there are several potential pitfalls.
- as a general rule, symlinks/symbolic links do not work well with quarto, so use something like 'realpath filename.qmd' to uncover the real path of your qmd file
- track down the path to your quarto
- set up an account on quarto-pub website
- publish your qmd to quarto-pub manually/interactively the first time (this automatically sets up a `_publish.yml` file which will help you automate. To do this, go your project with the qmd, then to the Terminal tab. at the prompt, enter:
`quarto publish quarto-pub filename.qmd`
you will be directed through several prompts to confirm your account and website name.
Check that the HTML publishes to a quarto-pub website, and that you like the output.
This will help generate the `_publish.yml` file.
Now you are ready to automate.
- for your cron job, use in 4 parts, all together on a single line (crontab does not allow line breaks)
1. `33 04 * * *` - cron schedule - this is 'every day at 4:33 AM'
2. `/app/apps/rhel8/quarto/1.5.54/bin/quarto`  path to your version of quarto - your path will be similar, but unique to your server/your version of quarto (note - keep your quarto version updated)
3. `publish quarto-pub` - command to publish to quarto-pub site 
4. `nfs/isilon/path-ibdx/shared_projects/foldername/filename.qmd` = path to your qmd file - your path will be similar, but unique to your server/your project
5. options `--no-prompt --no-browser` - so that it uses the `_publish.yml` file rather than interactively prompting you
6. `>>` - pipes resulting stuff to a log file
7. `/home/user/data_space/shared_projects/foldername/siteupdate.log` - path to log file
8. `2>&1` - instructions to pipe both the errors (STDERR = 2) and output (STDOUT = 1) to both be appended the log file
so the whole long line for the cronjob looks something like this:

`33 04 * * * /app/apps/rhel8/quarto/1.5.54/bin/quarto publish quarto-pub nfs/isilon/path-ibdx/shared_projects/foldername/filename.qmd --no-prompt --no-browser >> /home/user/data_space/shared_projects/foldername/siteupdate.log 2>&1`

then save your crontab, and check that your HTML updates correctly.

It may be helpful to add a a timestamp (with `print(Sys.time())`)to your qmd to be sure of updates

If you have problems, look at the log file.

Best wishes in automating with cron.

**Comment by ChrisKornaros** [comment]
I just got this error as well. I was able to write the output of a Quarto website to "." and had been doing so for a few days. Tonight that changed and I wasn't able to successfully render the website, or so I thought. It turns out I started getting this error message, pasted below, but it isn't actually affecting the HTML render. So, when I push changes to my repo, it updates the site on GitHub Pages.

Not sure how to share my entire file structure to recreate it, but I thought it should be brought up. I believe the error happened when I was messing around with enabling cookies and/or RSS feeds, and something with that feature broke the STDOUT message.


[ 1/18] index.qmd
[ 2/18] pages/blogs/posts/first_blog.qmd
[ 3/18] pages/blogs/blogs.qmd
[ 4/18] pages/projects/data_science/posts/titanic.qmd
[ 5/18] pages/projects/data_science/posts/gym_market.qmd
[ 6/18] pages/projects/data_science/posts/netflix.qmd
[ 7/18] pages/projects/data_science/posts/nfl_bowl_2025.qmd
[ 8/18] pages/projects/data_science/posts/login_validation.qmd
[ 9/18] pages/projects/data_science/data_science.qmd
[10/18] pages/projects/data_engineering/data_engineering.qmd
[11/18] pages/projects/data_engineering/posts/oss_data_arch.qmd
[12/18] pages/projects/data_engineering/posts/bank_etl.qmd
[13/18] pages/projects/data_engineering/posts/basic_oss.qmd
[14/18] pages/projects/projects.qmd
[15/18] pages/about/about.qmd
[16/18] pages/guides/posts/uv.qmd
[17/18] pages/guides/posts/quarto.qmd
[18/18] pages/guides/guides.qmd

ERROR: Source and destination cannot be the same.

Stack trace:
    at copyTo (file:///Applications/quarto/bin/quarto.js:41623:15)
    at updateSitemap (file:///Applications/quarto/bin/quarto.js:96287:9)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async websitePostRender (file:///Applications/quarto/bin/quarto.js:99169:5)
    at async Object.postRender (file:///Applications/quarto/bin/quarto.js:99135:9)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:86440:13)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:90843:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8111:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:8001:20)
    at async quarto (file:///Applications/quarto/bin/quarto.js:126627:9)

**Comment by mcanouil** [comment]
@ChrisKornaros 
Could you share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us to recreate your problem so that we can fix it: please help us help you! Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by ChrisKornaros** [comment]
Hey, sorry about the delayed response, the full repository is public: https://github.com/ChrisKornaros/ChrisKornaros.github.io

This is the commit where things broke, and the error happened as I described: 14fd5c1a67f5943cd37496dbadef3eed9758ce79

This is the commit before where things were still working:
78b08817d41422cad280cca8968f5cf02c3b6f72

This is the commit where I fixed the error:
6fc02d7188595f2805ef9b53557b311240abc6c0

**Comment by cderv** [comment]
From the stack trace you share at https://github.com/quarto-dev/quarto-cli/issues/10276#issuecomment-2544409774, the error seems to be from 
https://github.com/quarto-dev/quarto-cli/blob/83a3b5af86d5f43f5f611009b2af8e74e94ffad3/src/project/types/website/website-sitemap.ts#L56-L62

This give us a hint on what happens: `context.dir` is the same as `output_dir` which goes against expectation and we don't handle this in `robot.txt` creation. 

THis happens because of this line 
https://github.com/ChrisKornaros/ChrisKornaros.github.io/commit/14fd5c1a67f5943cd37496dbadef3eed9758ce79#diff-3f031d554ecb9bfd2f5476e72e2b804060b60a37eaa6a94610ffde2e7eaa8d45L3
when you tried to change `output-dir`
````yaml
project:
  type: website
  output-dir: .
````

The error was fixed in https://github.com/ChrisKornaros/ChrisKornaros.github.io/commit/6fc02d7188595f2805ef9b53557b311240abc6c0
because you remove `robot.txt`

So we definitely have an issue here, but I see two path forwards

- `output-dir` shouldn't be set as the Quarto root project. I am really unsure that our Quarto Project logic for Website and Books will correctly handle this 🤔 I believe we have an expectation of a clean different directory. Though I may be wrong as we take precaution to not remove the directory when we clean output dir 
https://github.com/quarto-dev/quarto-cli/blob/83a3b5af86d5f43f5f611009b2af8e74e94ffad3/src/command/render/project.ts#L311-L320

- We need to make `robot.txt` creation robust when there is not copy to be done because project dir is equal to ouput dir. 


> I was able to write the output of a Quarto website to "." and had been doing so for a few days. 

Can you explain more about this usage ? Honestly I am not sure we should permit this, I believe it could the source of other issues 🤔 

@cscheid what is your expectation on `output-dir`. Do we permit to be `.` so the same as Quarto project directory ? 

Thanks

**Comment by cscheid** [comment]
`output-dir: .` seems a bit risky to me. I'd prefer to know how common the usage is before making a change, but I think it would be reasonable for Quarto to disallow that.

**Comment by cscheid** [comment]
@ChrisKornaros I don't think your GH pages statement is accurate - we publish to github pages pretty extensively with Quarto, and `quarto publish gh-pages` doesn't require that.

**Comment by mcanouil** [comment]
The statement is indeed incorrect.
If you want to commit/push using `docs`, you can `output-dir: docs`.
It will work I can guarantee that.

Of course, if you set `output-dir: docs/_site` as you suggested, then il will also work but the extra directory will be required to access the site: `https://username.github.io/repository/_site`.

**Comment by ChrisKornaros** [comment]
@cscheid Correct, I'm not using `quarto publish` I'm using the `quarto render > git push` workflow from the main branch for simplicity, which limits the site directory to one level below repo root. 

Based on this thread, it seems like the behavior I experienced is intended and expected. It seems using `quarto publish gh-pages` is the better workflow, I'll update my workflow and directory to follow your suggestions. @mcanouil that's very helpful I think this can be closed, thank you both for the help!
