### ISSUE TITLE
Latex behaviour changed with new lualatex cngine

### ISSUE THREAD

**Issue by nithinmkp** [quarto-dev/quarto-cli#13616]
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [x] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

I am trying to compile a manuscript project made in quarto. It was working fine till I updated quarto to latest version.  Now when i compile , it is showing internal error and please file bug report

[Github](https://github.com/nithinmkp/paper-applied)

I know i should not share such large repo but other than this repo there doesnt seem to be an issue

### Steps to reproduce

Simply try to compile main.qmd

### Quarto check output

Quarto 1.8.25
[>] Checking environment information...
      Quarto cache location: C:\Users\Nithin M\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.87.0: OK
      Deno version 2.3.1: OK
      Typst version 0.13.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.8.25
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2025.09
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\ProgramData\TinyTeX\bin\windows\
      Version: 2025

[>] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
      Source: Windows Registry

**Comment by mcanouil** [comment]
Accessibility: For better accessibility, please ensure link text is descriptive and meaningful rather than using generic terms such as "here". This helps all users understand the link's destination. See [Writing meaningful link text (WCAG)](https://www.wcag.com/blog/writing-meaningful-link-text/).

---

Your repository is not accessible.

To help us investigate this issue effectively, we'll need a minimal reproducible example that isolates the problem. Unfortunately, the Quarto team doesn't have the time to extract this from your full repository.
Creating a simplified version that demonstrates the LaTeX compatibility issue with LuaLaTeX will need to be done on your end. This involves identifying the specific LaTeX components that are causing the conflict with LuaLaTeX.
We understand this requires effort, but a focused example is essential for us to pinpoint the root cause and provide an effective solution. Once you're able to provide a minimal reproducible example, we'll be happy to investigate the issue promptly.

Note that you can choose whatever PDF engine you want: https://quarto.org/docs/output-formats/pdf-engine.html#alternate-pdf-engines

**Comment by nithinmkp** [comment]
Thanks. I have tried to isolate the problem. The I have also tried to make the example as minimal as possible

Here is the Gtihub Repo [link](https://github.com/nithinmkp/latex-change)

Steps to Reproduce the issue
Problem 1
Earlier when we were using child documents, including references.bib as YAML in child docuemts worked, this was simple for inline citations. Now the same is causing issue. This causes additional problems like below

<img width="542" height="328" alt="Image" src="https://github.com/user-attachments/assets/16ac24da-9fb6-4d77-9d81-c10d47f50200" />

Problem 2
This comes from including 02-tables.qmd. To isolate this I just included only 01-intro.qmd and 02-tables.qmd in my main.qmd file.
The output
````
1: Div ("",["quarto-scaffold"],[]) [RawBlock (Format "latex-merge") "\\begin{table}",Plain [Span ("",["quarto-scaffold"],[]) [RawInline (Format "latex") "\\caption",RawInline (Format "latex") "{",Span ("",["quarto-scaffold"],[]) [RawInline (Format "latex") "\\label",RawInline (Format "latex") "{",RawInline (Format "latex") "tbl-desc",RawInline (Format "latex") "}"],RawInline (Format "latex") "Descriptive Statistics",RawInline (Format "latex") "}"]],Div ("",["quarto-scaffold"],[]) [Plain [RawInline (Format "latex") "\\centering",RawInline (Format "latex") "{"],RawBlock (Format "tex") "\n    \\centering\n     % Overall table caption\n    \n\n    \\small % Reduce font size\n\n    % Subtable 1 caption\n    \\caption*{(a): Demographic Variables} \n\n    % First Subtable: Table 1(a)\n    \\begin{subtable}{\\textwidth}\n    \\label{tbl-des_a}\n        \\centering\n        \\renewcommand{\\arraystretch}{0.9}\n        \\begin{tabular}{p{5cm} c}\n            \\toprule\n            \\textbf{Variable} & \\textbf{Mean/Proportion} \\\\\n            \\midrule\n            Income & 19,834.12 \\\\\n            Age & 46.34 \\\\\n            \\addlinespace\n            \\textbf{Education} & \\\\\n            \\quad Less than 5 & 27.5 \\\\\n            \\quad 5-10 & 56.4 \\\\\n            \\quad 10-12 & 8.7 \\\\\n            \\quad 13-15 & 7.0 \\\\\n            \\quad 15+ & 0.4 \\\\\n            \\addlinespace\n            \\textbf{Gender} & \\\\\n            \\quad Male & 88 \\\\\n            \\quad Female & 12 \\\\\n            \\addlinespace\n            \\textbf{Marital Status} & \\\\\n            \\quad Married & 85 \\\\\n            \\quad Unmarried & 15 \\\\\n            \\addlinespace\n            \\textbf{Geographic Location} & \\\\\n            \\quad Rural & 25 \\\\\n            \\quad Urban & 75 \\\\\n            \\addlinespace\n            \\textbf{Occupation} & \\\\\n            \\quad Agriculture and Allied & 15.4 \\\\\n            \\quad Manufacturing, Industry and Auto & 34.1 \\\\\n            \\quad Services, Media, Health & 50.3 \\\\\n            \\quad Others & 0.2 \\\\\n            \\bottomrule\n        \\end{tabular}\n        \\label{tbl-desc-a}\n    \\end{subtable}\n\n    \\vspace{1.5em} % Add some vertical space between subtables\n\n    % Subtable 2 caption\n    \\caption*{(b): Sentiment Variables} \n\n    % Second Subtable: Table 1(b)\n    \\begin{subtable}{\\textwidth}\n    \\label{tbl-des_b}\n        \\centering\n        \\renewcommand{\\arraystretch}{0.9}\n        \\begin{tabular}{p{3cm} p{2cm} c c c c c c}\n            \\toprule\n            \\textbf{Variable} & \\textbf{Response} & \\multicolumn{2}{c}{\\textbf{Full Sample}} & \\multicolumn{2}{c}{\\textbf{Pre-Covid Periods}} & \\multicolumn{2}{c}{\\textbf{Covid Periods}} \\\\\n            \\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}\n            & & \\textbf{N} & \\textbf{\\%} & \\textbf{N} & \\textbf{\\%} & \\textbf{N} & \\textbf{\\%} \\\\\n            \\midrule\n            QFP & Bad & 12,610 & 21.4 & 5,097 & 12.9 & 7,513 & 38.8 \\\\\n                & Same & 34,245 & 58.2 & 24,010 & 60.8 & 10,235 & 52.9 \\\\\n                & Good & 12,016 & 20.4 & 10,407 & 26.3 & 1,609 & 8.3 \\\\\n            \\addlinespace\n            QBC & Bad & 13,671 & 23.2 & 5,544 & 14.0 & 8,127 & 42.0 \\\\\n                & Same & 30,628 & 52.0 & 20,894 & 52.9 & 9,734 & 50.3 \\\\\n                & Good & 14,572 & 24.8 & 13,076 & 33.1 & 1,496 & 7.7 \\\\\n            \\midrule\n            \\multicolumn{2}{l}{Total N} & 58,871 & & 39,514 & & 19,357 & \\\\\n            \\bottomrule\n        \\end{tabular}\n        \\label{tbl-desc-b}\n    \\end{subtable}\n\n",Plain [RawInline (Format "latex") "}"]],Plain [],RawBlock (Format "latex-merge") "\\end{table}%"]
FATAL (C:/Program Files/Quarto/share/filters/main.lua:557) An error occurred:
This is an internal error. Please file a bug report at https://github.com/quarto-dev/quarto-cli/
2: RawBlock (Format "tex") "\\FloatBarrier"
Error running filter C:/Program Files/Quarto/share/filters/main.lua:
C:/Program Files/Quarto/share/filters/main.lua:1176: FATAL QUARTO ERROR
stack traceback:
        C:/Program Files/Quarto/share/filters/main.lua:2619: in function 'fatal'
        C:/Program Files/Quarto/share/filters/main.lua:2199: in function 'fail'
        C:/Program Files/Quarto/share/filters/main.lua:2204: in function 'internal_error'
        C:/Program Files/Quarto/share/filters/main.lua:557: in function <C:/Program Files/Quarto/share/filters/main.lua:550>
        (...tail calls...)
        C:/Program Files/Quarto/share/filters/main.lua:1176: in upvalue 'has_custom_nodes'
        C:/Program Files/Quarto/share/filters/main.lua:1192: in local 'postprocess_render'
        C:/Program Files/Quarto/share/filters/main.lua:1220: in local 'filter_fn'
        C:/Program Files/Quarto/share/filters/main.lua:653: in function <C:/Program Files/Quarto/share/filters/main.lua:643>
        (...tail calls...)
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:34: in upvalue 'run_filter_function'
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:223: in function <...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:202>
        (...tail calls...)
        [C]: in function 'pandoc.List.map'
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:125: in upvalue 'recurse'
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:222: in local 'jogger'
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:171: in upvalue 'recurse'
        ...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:222: in function <...uarto\share\pandoc\datadir\..\..\filters\modules/jog.lua:202>
        (...tail calls...)
        C:/Program Files/Quarto/share/filters/main.lua:572: in function <C:/Program Files/Quarto/share/filters/main.lua:550>
        (...tail calls...)
        C:/Program Files/Quarto/share/filters/main.lua:1314: in local 'callback'
        C:/Program Files/Quarto/share/filters/main.lua:1332: in upvalue 'run_emulated_filter_chain'
        C:/Program Files/Quarto/share/filters/main.lua:1368: in function <C:/Program Files/Quarto/share/filters/main.lua:1365>
WARN: Error encountered when rendering files
````
The same happens while including 03-model.qmd and also 04.figures.qmd. Such issues was not there untill july 14 when i last compiled a full blown version of this project

**Comment by cderv** [comment]
> Earlier when we were using child documents, including references.bib as YAML in child docuemts worked, this was simple for inline citations.

Can you give more details on what you where trying to achieve before ? 

By child, you mean "included" document using `{{< include ... >}}` right ? 

I see you are using this YAML frontmatter in each doc
````
---
bibliography: references.bib
---
````

As explained in our [doc page for include](https://quarto.org/docs/authoring/includes.html): 
> Include shortcodes are equivalent to copying and pasting the text from the included file into the main file. (...)
> It also means that if the included file has a metadata block, that block will take effect in all included files. In most cases, having metadata blocks in an included file will cause unexpected behavior.

So the last included doc to have a `bibliography` field will have its value override all the others. This is different than using a list of bib file 
````
bibliography:
  - bib1.bib
  - bib2.bib
````

So I am surprised this would have worked before... Was it working somehow ? Or were you doing differently ? 

In the meantime, I am looking at the other issue. 

Also a note
````
WARNING (C:/Users/chris/scoop/apps/quarto-prerelease/current/share/filters/main.lua:13985) Unable to resolve crossref @fig-ics
WARNING (C:/Users/chris/scoop/apps/quarto-prerelease/current/share/filters/main.lua:13985) Unable to resolve crossref @sec-4
WARNING (C:/Users/chris/scoop/apps/quarto-prerelease/current/share/filters/main.lua:13985) Unable to resolve crossref @fig-mean_educ
````

In your reproducible example you have three references that have no matching id. Is that expected from making your original example more minimal ?

**Comment by mcanouil** [comment]
FWIW, if the issue is really the PDF engine change to LuaLaTeX, setting back the engine to XeLaTeX should make the compilation works.

- https://quarto.org/docs/output-formats/pdf-engine.html#alternate-pdf-engines

**Comment by cderv** [comment]
The shared repo has xelatex https://github.com/nithinmkp/latex-change/blob/8bf34afd797e6933cccd6cd9744d23b60d183ddf/_quarto.yml#L8-L10
````yaml
format:
     pdf: 
       pdf-engine: xelatex
````

And I still get the internal error, so I think there is more than that; I'll be looking

**Comment by nithinmkp** [comment]
Yes. The cross ref can be ignored. The issue is internal and quarto cli itself recommended to file bug issue.
Regarding the first question of bib, I was using exactly similar way till July 2025. It worked fine. Adding
---
bibliography: references.bib
---
in front matter of every document helped for easier citations. That was the only purpose. It did not cause any weird behavior then. Now that is causing a issue in numbering. Any document that doesn't have front matter works well. 
Also when i tried to create this minimal example, it once worked. But then too it had its own problems. After that compilation once, it started with all errors and further compilation was not possible

<img width="563" height="533" alt="Image" src="https://github.com/user-attachments/assets/f6790991-3bdc-4432-88a2-ef6b834097b1" />
<img width="561" height="642" alt="Image" src="https://github.com/user-attachments/assets/00b1c3ba-04ec-4e21-9c60-763ff71d4186" />

Here i am pretty sure I am doing intext cross reference of figure correctly, but the reference was not recognized. Again this worked earlier. I looked in to the .tex file to understand the issue. what i understood is this. 
"My cross ref label is `mean_educ' where the '_' is escaped and hence label not generated. But this was not the case earlier

**Comment by cderv** [comment]
Your example not being that minimal there may be several issues. 

However, the fatal error comes from `.content-visible` when in Manuscript context. 

I removed everything except the following 

````
.
├── main.qmd
├── _manuscript
└── _quarto.yml
````

and modified `main.qmd` to 
````markdown
---
title: "some title"
---

::: {.content-visible when-format="pdf"}

```{=tex}
\begin{table}
    \centering
    \caption{Test Table}
    \label{tbl-test}
    \begin{tabular}{l c}
        \toprule
        A & B \\
        \midrule
        1 & 2 \\
        \bottomrule
    \end{tabular}
\end{table}
```

:::

````

and `_quarto.yml` to
````yaml
project:
  type: manuscript

manuscript:
  article: main.qmd

format:
  pdf: 
    pdf-engine: xelatex
    keep-tex: true

````

And I still have 
`````
FATAL (C:/Users/chris/Documents/DEV_R/quarto-cli/src/resources/filters/./ast/customnodes.lua:72) An error occurred:
This is an internal error. Please file a bug report at https://github.com/quarto-dev/quarto-cli/
`````

Looking deeper, I tried to simplify again and see if this was table related and it is not as it fails with `main.qmd` being

````markdown
---
title: "some title"
---

::: {.content-visible when-format="pdf"}

```{=tex}
\textbf{Hello World}
```

:::
````

So it is related to rawBlock inside `.content-visible` block, when using manuscript format. 

It does not happen when using default project
````yaml
project:
  type: default
````

This should give us enough clue to find about this fatal error.

**Comment by cderv** [comment]
Also it was working with 1.6.42 so you may have updated from there to latest.

**Comment by nithinmkp** [comment]
Exactly. It was working till quarto 1.72 something.

**Comment by cderv** [comment]
So this is deeper root cause, and something related to how we traverse, and some processing from manuscript.lua. 

It has nothing to do with RawBlock. This is all about conditional block being unsupported in manuscript, as this fails to

````markdown
---
title: "some title"
---

::: {.content-visible when-format="pdf"}

Something

:::

````

Somehow, this is the part failing
https://github.com/quarto-dev/quarto-cli/blob/a5e40c307e08daf1f10de8d4fe2a6ff97697ae4c/src/resources/filters/ast/customnodes.lua#L65-L75

because `node` is 
````
1: Para [Str "Something"]
````

and has no `walk` method, but is not empty. Which is not expected. 

It seems to be a List. 

After a long research, I found that `manuscript.lua` is creating a list element. 

https://github.com/quarto-dev/quarto-cli/blob/a5e40c307e08daf1f10de8d4fe2a6ff97697ae4c/src/resources/filters/layout/manuscript.lua#L56-L67

All div content are lifted which impact the conditional one 

modifying to using Blocks solves the issue
````diff
@@ -57,10 +56,10 @@ function manuscript()
         -- If this is a notebook embed cell, 'lift' the contents of any child divs
         -- up (unroll their contents), this will help us avoid
         -- labeling divs marked as `cells` more than once
-        local blocks = pandoc.List()
+        local blocks = pandoc.Blocks({})
         for _, childBlock in ipairs(divEl.content) do
           if is_regular_node(childBlock, "Div") then
-              tappend(blocks, childBlock.content)
+              blocks:extend(childBlock.content)
           else
             blocks:insert(childBlock)
           en
````

I believe this is the right fix, unless the `checked_walk()` function needs to consider Leaf node (those that don't have `:walk()` method but not empty. However, I think it would have been considered from the start and would be broader issue probably.

**Comment by nithinmkp** [comment]
That's brilliant work!! So what's the fix I wait untill quarto 1.9??

**Comment by cderv** [comment]
> So what's the fix I wait untill quarto 1.9??

I have made a PR, then once merge, this will be in main branch, and then the next pre-release 1.9. 

If we do a patch, this is will be next 1.8 stable patch release. 

So yes, you still need to wait a little more 😃

**Comment by nithinmkp** [comment]
can i use this now? pass this manuscript.lua as filter? or wait till patch or new version?

**Comment by cderv** [comment]
New pre-release is out, and this has been fixed in 1.8.26 latest patch release. So yes you should be able to use it

**Comment by nithinmkp** [comment]
Thanks. Now it gets compiled. However the issue of 

````
---
bibliography: references.bib
---
````
using above style in each individual document is still having issue like mentioned when i opened this issue. It was working fine earlier. I understand that this style is not prefered, i could do away with that. But using this in each document helps for easier citations inside each document especially when i work in VScode and Positron ( pressing @ gives me list of citations). If i dont include that YAML in all documents, citations become difficult

**Comment by cderv** [comment]
@nithinmkp please do open a new issue with detailed example for this one. One topic per ticket is way easier for us to look at. 

Like I mentioned, using `include` shortcode is like a copy-paste of the included content in the main one. So by setting `bibliography` in each, you are overriding the field each time. 

Maybe something change but this is the way it works with `include`. 

If you can give us detail in a new issue **when** your example (https://github.com/nithinmkp/latex-change) was working for you, this will help us. Thanks !

**Comment by mcanouil** [comment]
To note that the `@` autocomplete feature does not come from Quarto CLI, but from the IDE.

**Comment by cderv** [comment]
> But using this in each document helps for easier citations inside each document especially when i work in VScode and Positron ( pressing @ gives me list of citations). If i dont include that YAML in all documents, citations become difficult

Yes - this would probably be a feature request for the visual editor to consider `bibliography` field in `_quarto.yml` if this is not the case already. If it only works with in-file one, I think the practical aspect of that.

**Comment by nithinmkp** [comment]
I checked with quarto 1.6.43 and this issue is not there. Of course i also
think this has something to do with IDE. Whats your take? does this support
broad principles of Quarto? or is it that this working in quarto 1.6.43 is
a glitch and moving forward we would like to have it not supported?

**Comment by mcanouil** [comment]
@nithinmkp Please, as requested, open a new discussion (or eventually new issue) with a fully depiction of the steps, environments, etc. needed to produce.
