### ISSUE TITLE
Quarto and R paths not found 

### ISSUE THREAD

**Issue by jmagosta** [quarto-dev/quarto-cli#1882]
While running the tutorial for running Quarto in VSCode, after having installed the quarto.msi package, and the VS code quarto extension, the render step fails with a "Quarto Installation not Found" popup. Of course attempting to re-install quarto results in a "do you want to remove quarto" message. 

I assume this is a path problem that was not updated by the install -- but you may want to verify and document this. 

I run VSCode typically from the WSL unbuntu shell, but in this case I ran it from "in windows", so it defaults to powershell for the terminal.

**Comment by jjallaire** [comment]
@dragonstyle I believe our installer should end up with Quarto available on the PATH, correct?

It looks like Quarto is installed at `C:\Users.\[Username]\AppData\Local\Programs\Quarto\bin`

What happens if you execute `quarto --version` at a terminal from within VS Code (what about `quarto --paths`)

**Comment by dragonstyle** [comment]
Yes we do add it to the path- would be helpful to confirm that it is there. For vscode specifically we’ve seen a restart of vscode sometimes required to pick up the new path. I believe we are attempting to send a window message to all windows to reload their path, but I’ve read that ymmv as not all applications respect the message…

**Comment by jmagosta** [comment]
Yes, the path is set.   But running quarto.cmd returns this error, either
in cmd or PowerShell:

C:\Users\joagosta>quarto --path
'findstr' is not recognized as an internal or external command,
operable program or batch file.

Since PowerShell is now the preferred windows shell you may want to replace
the .cmd file with a .ps1 file.

______________
John Mark Agosta

**Comment by jthomasmock** [comment]
Adding two Community threads where folks ran into problems:
- [quarto: command not found - solved via `quarto.cmd`](https://community.rstudio.com/t/bash-quarto-command-not-found/144187/2)
- [quarto: render w/ Quarto Error - related to pandoc + Windows Server](https://community.rstudio.com/t/render-with-quarto-error/134403/37)

**Comment by jjallaire** [comment]
findstr issue addressed here: https://github.com/quarto-dev/quarto-cli/commit/aafefd78031f39dfad1783fa18581c0689d9252a

I think the rest of this will be well addressed by providing PowerShell, Git Bash, and CMD friendly scripts for Quarto. We will do this in v1.2

**Comment by mcanouil** [comment]
There have quite few updates in Quarto installers/builds.
Is the issue still there with Quarto 1.3 (or 1.4 pre-release)?
