### ISSUE TITLE
VS Code not finding Quarto after updating to latest version

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#2143]
### Bug description

After installing the latest Quarto version on Windows 11, VS Code no longer finds the quarto app when clicking on the render button when working on a `.qmd` file. I've restarted Windows after the install.

![image](https://user-images.githubusercontent.com/10863809/186902890-93fa25cb-e38a-4c0a-9ebb-7f0327ae70d8.png)

This is despite being able to run `quarto check`  from the VS code terminal
```
quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.132
      Path: C:\Users\xxx\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: C:/Users/xxx/anaconda3/python.exe
      Jupyter: 4.11.1
      Kernels: julia-1.4, julia-1.6, julia-1.7, python3, iota

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Users/xxx/OneDrive/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.3/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
How did you install Quarto on your Windows ?
Do you have anything in Quarto:Path configuration in VSCODE extension ? 
Is `quarto` found outside of VSCODE in Terminal ? Is it in PATH ? 

Just a trying to get a bit more information to understand what could have happened.

Thank you.

**Comment by jpmorr** [comment]
Installed quarto using the latest installer from the website - quarto-1.1.132-win.msi. `Quarto: Path` in VS Code points to the installation directory `C:\Users\xxx\AppData\Local\Programs\Quarto\bin`.

Quarto check runs from my windows terminal. it just seems that VS code extension no longer sees it.

**Comment by cderv** [comment]
Possibly related to this issue reported in VSCODE extension directly: https://github.com/quarto-dev/quarto-vscode/issues/63

It seems that you are not the only one with issue.

**Comment by jpmorr** [comment]
Hmmm, sounds like it could be the same issue in VS Code but I've also come across another issue related to the update where `quarto`  is failing a validation check when i try to run from my terminal. I had been using some some custom `yaml` parameters to pass to the `_titlepage.tex` as discussed in this thread: https://github.com/quarto-dev/quarto-cli/discussions/2060#discussioncomment-3455375.

So I think two separate issues related to the install. Should I open a new bug report for this second issue?

Regards,
JP

**Comment by cderv** [comment]
> but I've also come across another issue related to the update where quarto is failing a validation check when i try to run from my terminal.

It seems like an issue different than VSCODE not finding `quarto` to me... 🤔 

> as discussed in this thread: https://github.com/quarto-dev/quarto-cli/discussions/2060#discussioncomment-3455375.

Are you talking about this ? 

> But unfortunately that doesn't work as the edition and isbn information are not found in the yaml parameters. I guess you can only access a predefined list of parameters and can't simply create your own?

I think this has been answered following your post. Metadata for variables needs to be passed another way, or referenced taking into account the `book` key. 

> Should I open a new bug report for this second issue?

It is always best to keep issues and thread separated if they are not strictly related.

**Comment by jpmorr** [comment]
I think they are related.

Yes, the solution from that thread no longer works with the latest version 1.1.132. I've uninstalled that version and gone back to 1.1.57 which works fine with the `book.isbn` solution from the windows terminal. That's a workaround for me now.

I'm realising that VS Code updated this morning and feel that may be the cause now, or at least a contributing  factor.

**Comment by cderv** [comment]
I have opened a new issue to separate the discussion.

**Comment by jjallaire** [comment]
Thanks again for reporting this. This was indeed a quarto-cli problem which has been fixed in v1.1.140: https://quarto.org/docs/download/

**Comment by jpmorr** [comment]
@jjallaire I've just tried 1.1.147 today but VS Code still refuse to render from the render button. Preview/Render work from the in-built terminal. 

Maybe this is related to the VS Code extension not playing nice with some recent changes in the CLI?

**Comment by jjallaire** [comment]
Could you see what is printed in the Debug Console (that's a pane alongside Terminal, Problems, etc.)

**Comment by jjallaire** [comment]
Is your terminal running Git Bash or PowerShell?

**Comment by jpmorr** [comment]
There's nothing in the debug console and the only thing unusual that I see is a little yellow `findstr` warning:
![image](https://user-images.githubusercontent.com/10863809/187034621-3f89bcbd-e925-4593-a50a-4be16b587a92.png)

It still gives the pop-up window when clicking on the render button. But quarto from the VS Code Terminal is working fine - in fact I think the preview command is working much better now when called from the terminal.

**Comment by jpmorr** [comment]
> Is your terminal running Git Bash or PowerShell?

Powershell

**Comment by jjallaire** [comment]
Interesting. That `findstr` was supposed to be resolved in v1.1 but it looks like the merge of another branch brought it back. I've just remedied here: https://github.com/quarto-dev/quarto-cli/commit/550979e823cdfef7484a4625356f264dad5f89a5 and we'll be rolling a new release of v1.1 soon (today) w/ this change.

That said, I'm not certain that this is the problem (will ping back here when the build is ready so you can check). I think the problem may be related to both our relying on the PATH to find Quarto (we probably need some additional checks for it in other known locations) as well as the fact that Quarto has a `.cmd` wrapper script which makes both invoking it and path escaping very funky. We are also re-writing that script as a native binary so hopefully that will help.

More soon as we make progress on these various fronts.

**Comment by jpmorr** [comment]
@jjallaire Thanks for the update. I'll check back later tonight or tomorrow morning.

**Comment by jjallaire** [comment]
Another question: Is Quarto installed globally (in Program Files) or a the user level? If the latter is there a space in your username?

**Comment by dragonstyle** [comment]
Version 1.1.149 which contains this fix is available here:

https://quarto.org/docs/download/

**Comment by jpmorr** [comment]
> Another question: Is Quarto installed globally (in Program Files) or a the user level? If the latter is there a space in your username?

@jjallaire quarto isn't installed globally, just for my user account - and no space in the username.

@jjallaire, @dragonstyle Just installed 1.1.149. Still not working, but slightly different warning now:
![image](https://user-images.githubusercontent.com/10863809/187037136-2c632c3a-04a5-42e7-ad99-dcec8b076ddd.png)

![image](https://user-images.githubusercontent.com/10863809/187037182-7c6aa978-3433-4717-98a4-59392dcf9ce9.png)

**Comment by jjallaire** [comment]
Okay, we've done a bunch of work here so let's have another go-round.

First, install the new release of quarto (v1.1.63): https://quarto.org/docs/download/

Then, the new release of the VS Code extension: (v1.34.0): https://marketplace.visualstudio.com/items?itemName=quarto.quarto

We have now completely forsaken the quarto.cmd wrapper script in favor of a proper executable. We also have put a bunch of proactive logic into the VS Code extension to look for installed versions of Quarto. Hopefully this works for you! (LMK in any case).

**Comment by jpmorr** [comment]
@jjallaire Yes!! All working.

VS Code required a restart rather than just reloading the extension after updating, but that was about it. Back to normal it seems.

**Comment by jjallaire** [comment]
Outstanding!!! Great to hear

**Comment by jav-ed** [comment]
I had a similar issue, when I tried to create a new project with vscode. My installation is not inside /opt, which was the solution for [here](https://github.com/quarto-dev/quarto-vscode/issues/28). However, its installation is on a local path. The terminal could find quarto as a command. Anyhow, vscode could not find an installed quarto CLI. The solution for me was restarting the linux machine.
