### ISSUE TITLE
Can't publish on quarto-pub

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#3941]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3940

<div type='discussions-op-text'>

<sup>Originally posted by **pnavaro** January 12, 2023</sup>
I am trying to publish on quarto-pub and I am stuck in a loop hole. I always get this message

```
The authorization saved for Quarto Pub is no longer valid.
  Please be sure you are logged into the correct Quarto Pub account in your
  default web browser, then press Enter to re-authorize.
[✓] Creating quarto-pub site
? Re-authorize account (Y/n) › Yes
? Authorize (Y/n) › Yes
```

I try a lot of things:
- Delete my account on quarto-pub and recreate (I used github and I change to email+passwd)
- Remove my account with `quarto publish accounts`
- Remove the directory `.quarto`
- Change my default browser (Safari, Firefox, Chrome)
- create a token and set the env variable `QUARTO_PUB_AUTH_TOKEN`

Thanks for your help

Pierre</div>

**Comment by i2z1** [comment]
I've got the same issue when trying to publish via RStudio IDE -- infinite loop for authorization.
My gitlab CI from yesterday has this error when publishing:
```
[✓] Preparing to publish site
ERROR: API Error: 401 (Unauthorized)  
```
Auth tokens renewal at quartopub.com has no effect, error is still remaining.

**Comment by softwarenerd** [comment]
Hi All,

We identified a configuration issue that was causing publishing to fail with an authorization error. The configuration is now fixed, and publishing is back online. We understand the root cause of the issue, so this won't happen again.

Apologies for the inconvenience!

Best,

Brian

**Comment by bhattmaulik** [comment]
I am still facing the same issue even after updating to quarto version 1.3.103.
