### ISSUE TITLE
Quarto presentation render fails on second try after deleting cache when using `cache` with `leaflet::addProviderTiles`

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#4149]
### Bug description

**Note:** I [reported this](https://community.rstudio.com/t/quarto-presentation-render-fails-on-second-try-after-deleting-cache-when-using-cache-with-leaflet-addprovidertiles/158757) over at community.rstudio.com, but I suppose that this is a better place for it.

I am using RStudio 2022.12.0 Build 353 with R version 4.2.2 Patched (2022-11-10 r83330) and knitr-1.41 on a Ubuntu  20.04.5 LTS installation.

I have identified a problem using `cache: true` in a quarto document that uses the `leaflet` package, specifically when using `addProviderTiles`. An example document that demonstrates the problem is below:

````
---
title: "test"
format: revealjs
---

## Create some random spatial data

```{r}
library(sf)
library(leaflet)

# List of volcanos -----------------------------------------
v = c("Volcán Villarica, Chile","Volcán Lonquimay, Chile")

lon = c("Volcán Villarica, Chile"=-71.93,
        "Volcán Lonquimay, Chile"=-71.58)
lon = lon[v]

lat = c("Volcán Villarica, Chile"=-39.42,
        "Volcán Lonquimay, Chile"=-38.38)
lat = lat[v]

volcanoes = data.frame(name=v,lon=lon,lat=lat)
volcanoes = st_as_sf(volcanoes,coords=c("lon","lat"),crs=4326)

lf = volcanoes |> leaflet() |> addTiles() |> addMarkers()
```

## This works with cache

```{r}
#| cache: true
lf
```

## This fails with cache on second render

```{r}
#| cache: true
lf |> addProviderTiles(providers$OpenTopoMap)
```
````

 The document renders without problem the first time before the `cache` exists, but the second time it fails with the following error about missing dependencies:

```
Error: path for html_dependency not found: /tmp/RtmpXpw2HT
Execution halted
```

Deleting the cache allows it to render again, but one looses the `cache` functionality.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@cderv Maybe you have expertise here? I'm not familiar with how the knitr cache works.

**Comment by dmkaplan2000** [comment]
I should note that I converted this presentation from Rpres format to qmd and that is when I noted the problem. As an Rpres presentation, it worked fine.

**Comment by cderv** [comment]
It is happening with R Markdown too. So definitely something going on **leaflet**, **knitr** and/or **rmarkdown**. I don't think it is directly Quarto related. I'll look closer to debug. thanks for the report !

**Comment by dmkaplan2000** [comment]
I only tried Rpres (where it worked, or at least it didn't create an error) and Quarto (where it did not), so can't say for Rmarkdown...

**Comment by cderv** [comment]
@dmkaplan2000 this is an issue with how **leaflet** HTML dependency for using tile providers works (loaded by `addProviderTiles`). I opened an issue there https://github.com/rstudio/leaflet/issues/843 and you can look at linked one there too. 

It using a temp file in a R temporary directory which does not exists anymore in a following render. So cache won't find the HTML dependency. 

I don't exactly know why you don't get error with Rpres though. Maybe because caching works a bit specifically between rendering that in Rmd or Qmd with **knitr**

Anyway, you can follow there - I'll close this on Quarto side. 

Thanks for the report!

**Comment by eroten** [comment]
For anyone looking for a workaround in quarto before gets [rstudio/leaflet#843](https://github.com/rstudio/leaflet/issues/843) resolved , try adding `screenshot.force: true` in the knitr options in `_quarto.yml`

```yml
 knitr: 
      opts_knit: 
        always_allow_html: yes
      opts_chunk: 
          screenshot.force: true
```

**Comment by michelk** [comment]
This bug persits.

**Comment by mcanouil** [comment]
@michelk could you open an issue mentioning this one and provide sufficient information as requested in the bug report template? Thank you.

**Comment by cderv** [comment]
@michelk please to update all of your R packages related to this issue. 

it has been fixed upstream in **leaflet** version 2.2.1 and **leaflet.providers** version 2.0.0

Be sure to have those versions installed. 

You can follow all the related links from the leaflet issue report linked above to see how this has been fixed. 

Hope this helps

**Comment by michelk** [comment]
@cderv Thanks for coming back to me. 

I still have the problem. Here is an example:
[tt.md](https://github.com/quarto-dev/quarto-cli/files/14576553/tt.md)


```
> library(leaflet)
> library(leaflet.providers)
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Zurich
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet.providers_2.0.0 leaflet_2.2.1          

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.4 compiler_4.3.3    magrittr_2.0.3    fastmap_1.1.1    
 [5] R6_2.5.1          cli_3.6.2         htmltools_0.5.7   crayon_1.5.2     
 [9] crosstalk_1.2.1   digest_0.6.35     rlang_1.1.3    
```

**Comment by cderv** [comment]
I can't reproduce using your file. It works for me ok. 

Please try in a fresh new session, and if it happens again, open a new issue by sharing your reproducible example. 

You can share using special syntax - no need to upload file always 
https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

**Comment by michelk** [comment]
Not sure what you mean with "fresh new session". I still get the error after deleting the cache files.

```
% rm -r tt_cache 
% rm -r tt_files 
% quarto render tt.qmd
    
    
    processing file: tt.qmd
    1/7                  
    2/7 [unnamed-chunk-1]
    3/7                  
    4/7 [unnamed-chunk-2]
    5/7                  
    6/7 [unnamed-chunk-3]
    7/7                  
    output file: tt.knit.md
    
    pandoc 
      to: html
      output-file: tt.html
      standalone: true
      section-divs: true
      html-math-method: mathjax
      wrap: none
      default-image-extension: png
      
    metadata
      document-css: false
      link-citations: true
      date-format: long
      lang: de
      title: Test Document
      date: today
      
    Output created: tt.html

% echo "# cuatro\nasdf" >> tt.qmd 
% quarto render tt.qmd           

    
    processing file: tt.qmd
    1/7                  
    2/7 [unnamed-chunk-1]
    3/7                  
    4/7 [unnamed-chunk-2]
    5/7                  
    6/7 [unnamed-chunk-3]
    7/7                  
    output file: tt.knit.md
    
    Error: path for html_dependency not found: /tmp/Rtmpg3beht/data_stars42be6bca06f7_425387
    Execution halted
```

**Comment by mcanouil** [comment]
You place your project elsewhere on your machine as if you were starting it from scratch.

**Comment by cderv** [comment]
> if it happens again, open a new issue by sharing your reproducible example.

@michelk as asked, please do open new issue. This time I have done it for you in #9058 so that we can continue discuss in its own thread. 

General advice: It is usually recommended (at least within this repo) to start a new issue with reproducible examples, and updated versions of tools, instead of adding more in a thread that is closed. This one is already 1 year old!  

Let's keep discussing in #9058 now - thanks
