### ISSUE TITLE
Page content jumps on page load

### ISSUE THREAD

**Issue by WillemSleegers** [quarto-dev/quarto-cli#491]
Clicking on a link in the navigation bar links to a new page, but for a brief moment you can see that the content starts at the top of the screen (under the navigation bar) and then jumps down a bit. I believe this is because the navigation bar floats at the top of the page and the content needs to adjust for the height of the navigation bar. You can see this when you make a default Quarto website.

I think it would be nice if it doesn't have that jumpiness (by default). 

And is there a way to fix it?

**Comment by dragonstyle** [comment]
Thanks for reporting this - I think we can make a few tweaks to improve this, and we will!

**Comment by dragonstyle** [comment]
This should be fixed here:

f7cde13c9bc81182fe8cb51f4992c70bff0e10ff

and in the next release (building now)... Thanks for reporting this!

**Comment by WillemSleegers** [comment]
Thanks! This seems to fix it for most of the pages on my website, although it does still happen on one of my pages. The page in question is a page that lists my blog posts (default type). Curiously, I have another page that is only a listing (grid type) and that one does not have this issue.

**Comment by WillemSleegers** [comment]
I think you can see it if you create a default blog in RStudio. If you click on the link in the top left corner, you can see the page jump still.

**Comment by WillemSleegers** [comment]
I've put up my code in a repository here: https://github.com/WillemSleegers/willemsleegers-quarto

It's a bit weird what's happening. If I run the code locally, I tend to see the issue if I go from another page to the Blog page. If I click on the Blog link in the navbar from the Blog page itself, it's inconsistent whether it jumps or not.

I also see that some .css and .js files are not being loaded in Safari while they do work in Chrome. In Chrome, clicking on the Blog link in the navbar shows some inconsistent jumping. Sometimes it jumps, sometimes it doesn't.

Actually, I see that some of the other pages also sometimes jump. It's as if there's a slight delay in the JS code to correct for the navbar height, which is sometimes executed quickly enough and sometimes not.
