### ISSUE TITLE
Translation fo `cs` not used - [WARNING] during render

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#5197]
### Bug description

When I run `quarto render` 
- in a website project
- with a project-wide `lang: cs` setting in `quarto.yml`,

I see:

```
[WARNING] Could not load translations for cs
  translations/cs.yaml: YAML parse exception at line 3, column 13:
  mapping values are not allowed in this context
[WARNING] The term Abstract has no translation defined.
```

And the language-relevant elements in the rendered documents are not translated.

_quarto_yml:

```yaml
project:
  type: website

website:
  title: "quarto-title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    lang: cs
    css: styles.css
    toc: true
```

Quarto 1.3.324
MacOS 13.4 beta

Quarto check (I do have R installed, not sure why that check fails.)

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.324
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.1.3
      Kernels: python3, ir

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
I think there something weird/wrong going on here.

```sh
quarto create-project --type website:blog demo-cs
cd demo-cs
echo "lang: cs" >> _quarto.yml
quarto render
```

Using latest 1.2

<img width="933" alt="image" src="https://user-images.githubusercontent.com/8896044/232253373-9ea92a26-c808-4a2a-8aeb-167becc309b9.png">

Using current dev version

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/8896044/232253451-0128c0ec-5f0c-42b2-b18d-1b2782ac8ca0.png">

**Comment by dragonstyle** [comment]
Thanks for letting us know about this! This looks to be an underlying issue in a translation file for Pandoc - I reported the issue here:

https://github.com/jgm/pandoc/issues/8787

We will take an update version of Pandoc in a future release which will ideally include a fix (it looks simple to me)!

**Comment by mcanouil** [comment]
It appears `lang: pl` causes the same error.
Note that it has been fixed upstream in Pandoc (see <https://github.com/jgm/pandoc/issues/8787>), but it is not yet part of a release.

**Comment by eitsupi** [comment]
I see similar error in `ja`.

```log
[WARNING] Could not load translations for ja
  data file translations/ja.yaml not found
[WARNING] The term Abstract has no translation defined.
```

Pandoc doesn't seem to have the `ja` translation file...
https://github.com/jgm/pandoc/tree/main/data/translations

**Comment by vaclavstepan** [comment]
In 1.3.450 the issue still persist, although it does apparently use the translation (output is rendered with fields translated to  Czech).

**Comment by mcanouil** [comment]
Pandoc was not upgraded in 1.3.
Please try 1.4 pre-release.

**Comment by dragonstyle** [comment]
The underlying issue with cs and pl are now resolved in Quarto 1.4. The warning regarding the Japanese translation is currently expected since Pandoc doesn't have translations for Japanese.

**Comment by stephen-huan** [comment]
> I see similar error in `ja`.
> 
> ```
> [WARNING] Could not load translations for ja
>   data file translations/ja.yaml not found
> [WARNING] The term Abstract has no translation defined.
> ```
> 
> Pandoc doesn't seem to have the `ja` translation file... https://github.com/jgm/pandoc/tree/main/data/translations

@eitsupi I have added Japanese translations in https://github.com/jgm/pandoc/pull/9930.
