### ISSUE TITLE
Rendering to ePUB then HTML breaks page links.

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#564]
If I render first to `epub` then to `html`, the links in the HTML document are broken.

I have been able to replicate this with the beginner book project from "Create New Project" -> "Quarto Book" through the RStudio IDE, and making some minor changes to the `_quarto.yml` as below: 

```yaml
project:
  type: book

book:
  title: "test"
  author: "Jane Doe"
  date: "07/04/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  epub:
    html-math-method: mathjax
  html:
    theme: cosmo

editor: visual
```

Rendering first to `epub` with:
```bash
quarto render --to epub
```

Then if I render to HTML with:
```bash
quarto render --to HTML
```

The index page will load fine, but all of the links from the TOC on the left link to a `.epub` URL instead of `.html`, i.e. the "Introduction" will link to: 
```
file:///Users/brady/Desktop/test/_book/intro.epub
```
If I then change the `.epub` to the `.html` the page will load. All of the links from the TOC on the left hand side seem to be similarly affected.

If I remove the epub entry from the YAML and re-render the document to HTML the links are correct.

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/d6e4e500e4195d3474018681b84ca12279d006aa (binary build w/ this fix will be available later today)

**Comment by BradyAJohnston** [comment]
I installed the version `0.9.209` from the github build, and I still get the same error if `epub` appears in the YAML before the `html` output option. If the HTML appears first then it renders fine.

**Comment by jjallaire** [comment]
I am not able to repro this anymore w/ the steps given above. It's possible that there is some leftover state in your project directory from the previous version (but I can't reason my way through exactly how this would affect things). Try deleting the `.quarto` directory from the project to see if this is the case.

**Comment by BradyAJohnston** [comment]
It seems that it only happens now when I do `quarto render` rather than `quarto render --to html`.

I am able to reproduce this in a new project from "New Quarto Book" with the YAML as below:

**Comment by jjallaire** [comment]
Sorry to be taking so long to get back to this, will repro and address soon!

**Comment by jjallaire** [comment]
Okay, we've finally got this all sorted: https://github.com/quarto-dev/quarto-cli/commit/99ea0a05b1cdbcbff21345c1c05e8c79dfb1c43d

This fix will be available in release 0.9.250 (should be out soon)

**Comment by BradyAJohnston** [comment]
Yep just tested on the latest build and the problem seems to be solved!
