### ISSUE TITLE
The error message for ojs cells is not being displayed

### ISSUE THREAD

**Issue by resmartiZH** [quarto-dev/quarto-cli#6267]
### Bug description

If I render a html file using quarto-1.3.433 containing ojs cells and open the file from file explorer without webserver an error message should be displayed telling me "The OJS runtime does not work with file:// URLs. Please use a web server to view this document." This message is not beeing displayed if embed-resources is set to "true". The reason is that `calloutBlock(opts)` is being called without a heading.

### Steps to reproduce
`````markdown
---
date: last-modified
lang: de
format: 
    html:
        theme: default
        embed-resources: true
        standalone: true

toc: true
toc-location: left 
toc-title: "Inhalt"

number-sections: true
number-depth: 3
code-fold: false

title-block-banner: "#0076BD"

fig-cap-location: top
fig-align: "left"

engine: knitr
execute:
  warning: false
  echo: false
---

# Test

````{ojs}
viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)
````
`````

### Expected behavior

There should be a alert telling me "The OJS runtime does not work with file:// URLs. Please use a web server to view this document." if i open the generated html-file from file explorer.

### Actual behavior

The error message as well a the content of the ojs cell is not being displayed. The console shows an error `Uncaught TypeError: Node.appendChild: Argument 1 is not an object.` This is caused by calling `calloutBlock(opts)` with the heading-attribute being undefined.

### Your environment

- R-Studio 2023.06.0 Build 421
- Quarto 1.3.433 (also with 1.3.353 or 1.4.234)
- Windows 10 Enterprise

### Quarto check output
```
Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Users\B251PRM\Documents\Rengine\02_Rstudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.0
      Path: C:/Users/B251PRM/Documents/Rengine/03_python/python-3.9/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

(-) Checking R installation...........Profile for Res Marti <> loaded.
[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/Users/B251PRM/Documents/Rengine/02_R/R-4.1.3
      LibPaths:
        - C:/Users/B251PRM/Documents/Rengine/02_R/R-4.1.3/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
`ojs` in general doesn't work well (arguably not all) with `embed-resources`. For reasons beyond our control, the ObservableJS engine calls out to the internet to fetch resources. So, I agree this is a bug, but even if we fixed this, the output likely wouldn't be what you expect.

**Comment by resmartiZH** [comment]
I understand, that the standalone html-files still won't display ojs cells if called from the file system. But I spent about two hours just finding out what the problem is, because there was just no error messag being displayed.
