### ISSUE TITLE
"image-placeholder" setting ignored when more than one listing on a page

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#6447]
### Bug description

If more than one listing is created for a page, and if the "image-placeholder" option is used for a listing, the image specified in the option is not used if a listing item does not have an image associated with it.  The listing item is simply shown with a blank field where the image should be.

### Steps to reproduce

Create a new blog project:

```
$ quarto create-project myblog --type website:blog
$ quarto preview myblog
```
Edit myblog/posts/welcome/index.qmd so that the image entry is commented out:

```
---
title: "Welcome To My Blog"
author: "Tristan O'Malley"
date: "2023-08-03"
categories: [news]
---

This is the first post in a Quarto blog. Welcome!

<!-- ![](thumbnail.jpg) -->

Since this post doesn't specify an explicit `image`, the first image in the post will be used in the listing page of posts.
```

Edit myblog/index.qmd so that it contains two identical listings with an image placeholder specified:

```
---
title: "myblog"
listing:
  - id: list1
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    image-placeholder: profile.jpg
  - id: list2
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    image-placeholder: profile.jpg
page-layout: full
title-block-banner: true
---

:::{#list1}
:::

:::{#list2}
:::
```

### Expected behavior

Since the "Welcome to my Blog" list entry doesn't have an image associated with it, the image placeholder profile.jpg should be used in the blog listings in the rendered index.html

### Actual behavior

The "Welcome to my Blog" list entry in each listing has no image associated with it.

### Your environment

Command line.

Linux Kubuntu 20.04

Quarto version: 1.4.217

**Comment by mcanouil** [comment]
I cannot reproduce when I fully render the website.
<img width="353" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/cf4c39eb-36cd-4fcf-8593-dffdd2ed201c">

Be sure your previous rendering is no longer there.

**Comment by dragonstyle** [comment]
Sorry I fixed this yesterday (but somehow didn't mark it fixed as intended). 

It is fixed here:
https://github.com/quarto-dev/quarto-cli/commit/3895a51d7cdbb0764423f8250f340131a72d1cde

It was related to using array syntax for listings.

**Comment by mcanouil** [comment]
Ok, this explained why I wasn't able to reproduce 😅

**Comment by Nesper94** [comment]
Hi, I still have this issue on version 1.4.554, is this normal?

**Comment by mcanouil** [comment]
Please open a new issue with a small reproducible example. Thank you!

**Comment by jlgraves-ubc** [comment]
It looks like a temporary work-around is just to make sure the placeholder image is being rendered elsewhere.

I added a hidden div (`:::{.hidden}`) with the image in it, and then it worked fine.

**Comment by cderv** [comment]
@jlgraves-ubc this should be fixed once on 1.4 and additional fixes for another cases in 1.5. 
You should try next prerelease version.
