### ISSUE TITLE
`tbl-colwidths` and table's label are incompatible in Quarto Book

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#7072]
### Bug description

`tbl-colwidths` and table's label are incompatible in Quarto Book.

### Steps to reproduce

Step 1: create book project 

```
quarto create-project mybook --type book
```

Step 2:  add an markdown table to `index.qmd`

````
See @tbl-Fruit

| fruit  | price  |
|--------|--------|
| apple  | 2.05   |
| pear   | 1.37   |
| orange | 3.09   |

: Fruit prices {#tbl-Fruit tbl-colwidths="[75,25]"}
````

Step 3: Render Book

### Expected behavior

Works as  https://quarto.org/docs/authoring/tables.html#column-widths

### Actual behavior

<img width="790" alt="tble" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/89143b6f-e3cb-4b79-8403-e8924a2c52d2">

### Your environment

- RStudio 2023.09.0+463 "Desert Sunflower" Release (b51c81cc303d4b52b010767e5b30438beb904641, 2023-09-25) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.0+463 Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36
- Quarto 1.4.388

### Quarto check output

```bash
quarto check
```
````
Quarto 1.4.388
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.388
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xiangyun/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

````

**Comment by cderv** [comment]
Just to add that this is not related to book. Minimal reproducible example would be with `format: html`

````markdown
---
title: "Minimal example"
format: html
---

See @tbl-Fruit

| fruit  | price  |
|--------|--------|
| apple  | 2.05   |
| pear   | 1.37   |
| orange | 3.09   |

: Fruit prices {#tbl-Fruit tbl-colwidths=[75,25]}
````

I get the same results.

**Comment by XiangyunHuang** [comment]
Your MWE means that cross-rerefence is still ok while not ok in Book project.

<img width="878" alt="截屏2023-09-29 18 19 28" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/e9487ffa-c139-4a40-a78e-b1259e729138">

**Comment by cderv** [comment]
Oh right I missed that part! Thanks for looking into this. So we have two issues !

* Attributes (like `tbl-colwidths`) not being catched up and process - this happens also outside of book project
* Cross reference does not work additionally in book project context

**Comment by cscheid** [comment]
Let's split this in two issues.

**Comment by cscheid** [comment]
I can't reproduce the crossref issue on latest `main` (and table widths are now corrected).

<img width="1076" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/9bd82432-86cb-4d20-9776-52a1aa300696">

**Comment by XiangyunHuang** [comment]
Thanks for the quick fix. How about release a new version? Because the latest Quarto [v1.4.392](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.392) is still not ok.
