### ISSUE TITLE
Embedded tables are not rendering in parent quarto document

### ISSUE THREAD

**Issue by atsyplenkov** [quarto-dev/quarto-cli#7210]
### Bug description

I am attempting to embed a table from one .qmd file into another .qmd file (parent document). However, regardless of how the table is rendered (using kable, gt, or hux), the embedding process causes the rendering to fail with the following errors. Individually, each quarto document renders successfully to .html.

```bash
processing file: index.qmd
                                                                                                    
output file: index.knit.md

Rendering qmd embeds
[1/1] notebooks/inset-table.qmd


processing file: inset-table.qmd
                                                                                                    
output file: inset-table.knit.md

ERROR: The notebook notebooks/inset-table.qmd doesn't contain output to embed with the cell id, tag, or label 'tbl-two'. Please be sure to have executed any cells that you are embedding.

Stack trace:
    at file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69578:23
    at Array.map (<anonymous>)
    at notebookMarkdown (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69573:40)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async replaceNotebookPlaceholders (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69517:32)
    at async renderPandoc (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69873:28)
    at async Object.onRender (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76312:36)
    at async renderFileInternal (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76289:17)
    at async renderFiles (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76084:17)
    at async render (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:81071:21)
```

### Steps to reproduce

There are two documents. One is the parent document, the second is the supplementary document (named `inset-table.qmd`).

# Parent document
````qmd
---
title: "Test of embedding tables"
format:
  html:
    toc: true
---

Hello world

```{r}
#| label: tbl-one
#| tbl-cap: This is normal gt table

gt::gt(head(mtcars))

```

{{< embed inset-table.qmd#tbl-two >}}
````

# Supporting document (`inset-table.qmd`)

````qmd
---
title: "Notebook"
---

```{r}
#| label: tbl-two
#| tbl-cap: THis is embed example

gt::gt(head(mtcars))

```
````

### Expected behavior

There should be two tables printed using the `gt` package in the parent document.

### Actual behavior

Quarto crashes with the following error

```bash
processing file: index.qmd
                                                                                                    
output file: index.knit.md

Rendering qmd embeds
[1/1] notebooks/inset-table.qmd


processing file: inset-table.qmd
                                                                                                    
output file: inset-table.knit.md

ERROR: The notebook notebooks/inset-table.qmd doesn't contain output to embed with the cell id, tag, or label 'tbl-two'. Please be sure to have executed any cells that you are embedding.

Stack trace:
    at file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69578:23
    at Array.map (<anonymous>)
    at notebookMarkdown (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69573:40)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async replaceNotebookPlaceholders (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69517:32)
    at async renderPandoc (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:69873:28)
    at async Object.onRender (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76312:36)
    at async renderFileInternal (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76289:17)
    at async renderFiles (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:76084:17)
    at async render (file:///C:/Users/TSYPLE~1/AppData/Local/Programs/Quarto/bin/quarto.js:81071:21)
```

### Your environment

- **IDE**: RStudio 2023.09.1+470 "Desert Sunflower" Release (ecb7e65667c9e2f54fdec9e313f24df8c7b71adc, 2023-10-04) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+470 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

- **OS**: Windows 10 Enterprise,  22H2,  OS build 19045.3570

- **R**:
```r

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Pacific/Auckland
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.33     utf8_1.2.3        R6_2.5.1          fastmap_1.1.1    
 [5] tidyselect_1.2.0  magrittr_2.0.3    glue_1.6.2        tibble_3.2.1     
 [9] htmltools_0.5.6   pkgconfig_2.0.3   gt_0.10.0         dplyr_1.1.3      
[13] generics_0.1.3    lifecycle_1.0.3   xml2_1.3.5        cli_3.6.1        
[17] fansi_1.0.4       vctrs_0.6.3       compiler_4.3.1    rstudioapi_0.15.0
[21] tools_4.3.1       pillar_1.9.0      rlang_1.1.1   

```

### Quarto check output

```bash
Quarto 1.4.415
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.415
      Path: C:\Users\%username%\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\%username%\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.5 (Conda)
      Path: C:/Users/%username%/Miniconda3/python.exe
      Jupyter: 5.3.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/%username%/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
I believe you are trying to use a Jupyter Notebook only feature: https://quarto.org/docs/authoring/notebook-embed.html

So it won't work with `engine: knitr`. @dragonstyle as it change ? Otherwise we could maybe try to stop early when we detect engine knitr and embed shortcode usage ?

**Comment by atsyplenkov** [comment]
> I believe you are trying to use a Jupyter Notebook only feature: https://quarto.org/docs/authoring/notebook-embed.html
> 
> So it won't work with `engine: knitr`. @dragonstyle as it change ? Otherwise we could maybe try to stop early when we detect engine knitr and embed shortcode usage ?

Thanks for the prompt response! I don't understand how than it work in `manuscript` projects. For example see — https://mine.quarto.pub/manuscripts-conf23/#/embedded-computations

Roughly speaking, the only difference between slides and mine reprex is that the project type wasn't specified. Could it be the reason?

**Comment by cderv** [comment]
Oh yes new manuscript format and features. Sorry - I missed that. 🤦  Thanks for additional content ! 

Recent work have support for .qmd embedding indeed using intermediary files. I see there was a bug with `fig-` at some point (https://github.com/quarto-dev/quarto-cli/issues/6959) so maybe there is one with `tbl-`. 

@dragonstyle will known more.

**Comment by atsyplenkov** [comment]
> Recent work have support for .qmd embedding indeed using intermediary files. I see there was a bug with `fig-` at some point (#6959) so maybe there is one with `tbl-`.

Sure it is! `tbl-cap` was the reason for the strange behavior. Moreover, it fully depends on the project type. For example, switching the project to the `manuscript` type will not throw an error, but it will not render tables (**example 1**). Removing `tbl-cap` in the `manuscript` type will result in rendering only the `knitr::kable` table (**example 2**). Removing the project type, i.e., reproducing [my initial issue](https://github.com/quarto-dev/quarto-cli/issues/7210#issue-1939136515) without `tbl-cap` options, will render only the `kable` table expanded to the full width (**example 3**). Note that the `gt` table failed to embed but did not throw any error, while the `kable` table embedded successfully but without the Table 3 heading!

It turns out that only `knitr::kable` tables could be embed, while `kableExtra`, `gt` and `hux` are not.

## Example 1
original issue switched to `manuscript` type with `tbl-cap`

![image](https://github.com/quarto-dev/quarto-cli/assets/34775595/4bd71a0e-c4de-43a5-870e-6b7e4ffcccf9)

## Example 2
original issue switched to `manuscript` type without `tbl-cap`

![image](https://github.com/quarto-dev/quarto-cli/assets/34775595/1a13850b-0cbc-4ed2-8e0f-e0fa6ae10885)

## Example 3
original issue without `tbl-cap` options

![image](https://github.com/quarto-dev/quarto-cli/assets/34775595/40902f2a-ccb2-4e77-8f29-5b5ec4a4ea46)

**Comment by dragonstyle** [comment]
Thanks for the additional details - I am tracking down the issues and think I know how to fix... will update here soon...

**Comment by dragonstyle** [comment]
This is resolved in the current Quarto pre-release.

**Comment by DOH-FAA3303** [comment]
@dragonstyle this still doesn't work with gt tables and a manuscript project type using quarto version 1.5.22 or 1.4.358. are there plans to add gt and other tables for manuscripts in the future? Or are there ways around this problem you know of?

**Comment by DOH-FAA3303** [comment]
> > Recent work have support for .qmd embedding indeed using intermediary files. I see there was a bug with `fig-` at some point (#6959) so maybe there is one with `tbl-`.
> 
> Sure it is! `tbl-cap` was the reason for the strange behavior. Moreover, it fully depends on the project type. For example, switching the project to the `manuscript` type will not throw an error, but it will not render tables (**example 1**). Removing `tbl-cap` in the `manuscript` type will result in rendering only the `knitr::kable` table (**example 2**). Removing the project type, i.e., reproducing [my initial issue](https://github.com/quarto-dev/quarto-cli/issues/7210#issue-1939136515) without `tbl-cap` options, will render only the `kable` table expanded to the full width (**example 3**). Note that the `gt` table failed to embed but did not throw any error, while the `kable` table embedded successfully but without the Table 3 heading!
> 
> It turns out that only `knitr::kable` tables could be embed, while `kableExtra`, `gt` and `hux` are not.
> 
> ## Example 1
> original issue switched to `manuscript` type with `tbl-cap`
> 
> ![image](https://private-user-images.githubusercontent.com/34775595/274736372-4bd71a0e-c4de-43a5-870e-6b7e4ffcccf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNTM3MjcsIm5iZiI6MTcwOTE1MzQyNywicGF0aCI6Ii8zNDc3NTU5NS8yNzQ3MzYzNzItNGJkNzFhMGUtYzRkZS00M2E1LTg3MGUtNmI3ZTRmZmNjY2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIwNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZThiMDM5YjNhMWVlODdkZTU4NDM0ZDBlZTk2YTM5NzM4OWY5Yjg0YjVkNzcyNTJkY2NiZDI5MTc0NDhhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwrsxcDCNkT4G9NvCjOrFtx3fAU9cHN10WDpdvflwxw)
> 
> ## Example 2
> original issue switched to `manuscript` type without `tbl-cap`
> 
> ![image](https://private-user-images.githubusercontent.com/34775595/274737458-1a13850b-0cbc-4ed2-8e0f-e0fa6ae10885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNTM3MjcsIm5iZiI6MTcwOTE1MzQyNywicGF0aCI6Ii8zNDc3NTU5NS8yNzQ3Mzc0NTgtMWExMzg1MGItMGNiYy00ZWQyLThlMGYtZTBmYTZhZTEwODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIwNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjczY2NjNDJkOTFiYjYzODBlNTM3ZDkxMmU2MzJkMGVjOTA4MjU0YjVmNGUzMDg5YmI5ZjNiNDg2ZTIwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jcg4znkh_M4TU5DhUaQsjZyYMFbOi0378nHuTGHbGKU)
> 
> ## Example 3
> original issue without `tbl-cap` options
> 
> ![image](https://private-user-images.githubusercontent.com/34775595/274735351-40902f2a-ccb2-4e77-8f29-5b5ec4a4ea46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNTM3MjcsIm5iZiI6MTcwOTE1MzQyNywicGF0aCI6Ii8zNDc3NTU5NS8yNzQ3MzUzNTEtNDA5MDJmMmEtY2NiMi00ZTc3LThmMjktNWI1ZWM0YTRlYTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIwNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOWVkODY5YTBkODQ0OTAxNGM2MTc4NjkwZTZkNmVmZmMxMzVlZjk0YTlmYTgwZjU0OThjNDIyZDczNjk3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YiGuVyyAr9yuyeijFF0AxI2QR3FQUjIGJlKVQmWAMDQ)

@mcanouil  I meant i reproduced this example exactly and was unable to render the gt table

**Comment by mcanouil** [comment]
Unfortunately, using screenshots is really a pain.
@DOH-FAA3303 since you tried somehow the examples, would you mind sharing a Git repository which could be use to reproduce the issue?

**Comment by DOH-FAA3303** [comment]
> Unfortunately, using screenshots is really a pain. @DOH-FAA3303 since you tried somehow the examples, would you mind sharing a Git repository which could be use to reproduce the issue (and possibly reopen the GitHub issue)?

I just submitted a new issue with the example in markdown @mcanouil
