### ISSUE TITLE
Quarto should clean windows temp files

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#7757]
### Bug description

I almost ran out of space today on my work computer and ended up looking at the temp folder and I see loads of folders created by quarto:

![image](https://github.com/quarto-dev/quarto-cli/assets/1813121/46383447-e4ee-447a-b256-bc64a6651d19)

Here's a screenshot of me trying to delete them

![image](https://github.com/quarto-dev/quarto-cli/assets/1813121/eb554c78-ef1e-4071-a3a4-9bc93256e626)

Do you know why the operating system isn't cleaning this? I have quarto files from earlier this year in here.

### Your environment

Windows 10 Enterprise

**Comment by cscheid** [comment]
We do clean up temporaries if the process finishes successfully (see eg `src/command/render/render-services.ts`).

One way in which temporary files might linger in the file system is if the process crashes. Assuming that's the source of these lingering files, (which are obviously a quarto bug!) we should probably have a single location in the file system that stores "files created by every session", which we could clean up at every quarto invocation.

**Comment by cscheid** [comment]
Digging into this a little bit further:

- We have only [one mention of `quarto-session` in our code](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/temp.ts#L35);
- We have [cleanup registration code for it](https://github.com/quarto-dev/quarto-cli/blob/main/src/quarto.ts#L143);
- And that cleanup is called on both [normal and abnormal termination of the quarto code](https://github.com/quarto-dev/quarto-cli/blob/main/src/quarto.ts#L201-L212)

I think `Ctrl + C` is to blame here.

**Comment by cscheid** [comment]
We could also attempt to do this cleanup [in the Windows launcher](https://github.com/quarto-dev/quarto-cli/tree/main/package/launcher), since it seems that Windows simply doesn't have great support for catching abnormal termination in-process.

**Comment by cscheid** [comment]
(@cderv, I assigned this to you because `windows`, just FYI)

**Comment by cscheid** [comment]
@cderv, I think we fixed this with our changes to project initialization. Would you mind confirming?

**Comment by cderv** [comment]
We still get the issue of no cleanup when abnormal termination because it is not active on windows
https://github.com/quarto-dev/quarto-cli/blob/3e8784e7270004f8ea1e8ff9497fb0b2879f4ff5/src/core/main.ts#L29-L33
https://github.com/quarto-dev/quarto-cli/blob/3e8784e7270004f8ea1e8ff9497fb0b2879f4ff5/src/core/main.ts#L75-L77

I remember we discussed that in https://github.com/quarto-dev/quarto-cli/pull/12329#issuecomment-2743993732 where I shared `SIGINT` is supported on windows. So we could do 

We could try to do it in a `finally` clause, as discussed, but I guess it would require wrapping in the correct place. I'll try what I understand from our discussion. 

What I can say following test is this works 
````diff
diff --git a/src/core/main.ts b/src/core/main.ts
index 25b45f5b6..c25041891 100644
--- a/src/core/main.ts
+++ b/src/core/main.ts
@@ -27,8 +27,8 @@ export async function mainRunner(runner: Runner) {
     await initializeLogger(logOptions(args));

     // install termination signal handlers
+    Deno.addSignalListener("SIGINT", abend);
     if (!isWindows) {
-      Deno.addSignalListener("SIGINT", abend);
       Deno.addSignalListener("SIGTERM", abend);
     }
````

To clean anything that is registered as a global cleanup handler when called 
https://github.com/quarto-dev/quarto-cli/blob/3e8784e7270004f8ea1e8ff9497fb0b2879f4ff5/src/core/cleanup.ts#L11-L26

New local project temp context won't be cleaned up though, as it is not registered this way.

**Comment by cderv** [comment]
> We could try to do it in a finally clause, as discussed, but I guess it would require wrapping in the correct place. 

So I tried it and the `finally` part does not seem be called when terminating program. I was puzzled on this from our discussion at https://github.com/quarto-dev/quarto-cli/pull/12329 but it seems expected. 

So we should either run the `abend()` on signal handler on Windows too. And we should add anything that should be unlocked and cleaned in the global cleanup handler. 

Or, if you think this is too risky, we need to have a cleanup leftover step at the next render so that any `$TEMP$/quarto-session*` and `.quarto/quarto-session-temp*` directories are removed before starting the new rendering. 

On Windows, we still have the unlock problem for `Deno.kv`. In case of termination, we may not unlock the databases if the unlock step is not in the global cleanup handler. Like
https://github.com/quarto-dev/quarto-cli/blob/19f27288b592f067364dbf0af28b605bf5fe8604/src/project/project-context.ts#L317-L321

Happy to discuss this live to solve for 1.7
