### ISSUE TITLE
Quarto website's bottom margin changes and the sidebar flashes when clicking on white space

### ISSUE THREAD

**Issue by zehuiyin** [quarto-dev/quarto-cli#8142]
### Bug description

On the quarto.org website, when the sidebar is enabled, clicking on a certain white space at the bottom of the webpage triggers a flash on the sidebar and alters the bottom margin of the webpage.

### Steps to reproduce

1. Go to https://quarto.org/docs/guide/
2. Click on the white space at the bottom of the webpage, where the div id is “quarto-sidebar-glass”

![Recording 2024-01-05 at 22 15 52](https://github.com/quarto-dev/quarto-cli/assets/107876618/7206ac62-691b-45a4-89f3-abef7bc3bc8d)

### Expected behavior

The webpage should remain unchanged when clicking on the sidebar glass.

### Actual behavior

The sidebar flashes briefly and the bottom margin of the webpage shrinks.

### Your environment

Windows 11
Google Chrome Version 120.0.6099.131 (Official Build) (64-bit)

**Comment by mcanouil** [comment]
I cannot reproduce after spending few minutes trying and don't really understand what you are doing as we don't even see the mouse clicks in your image.

**Comment by zehuiyin** [comment]
Hi Mickaël,

Thank you for your prompt reply!

I tested the issue on another browser (Microsoft Edge) and recorded my mouse clicks as yellow circles.

To reproduce the issue, please follow these steps:
1. Go to https://quarto.org/docs/guide/
2. Scroll down the webpage
3. Click on the white space at the bottom of the webpage above the footer

You can see the screen capture gif:
![Recording 2024-01-06 at 12 08 30](https://github.com/quarto-dev/quarto-cli/assets/107876618/e4f1a38c-fd29-4568-ab57-a8a67b061d63)

The last two clicks caused the sidebar to flash and the bottom margin to disappear.

**Comment by mcanouil** [comment]
It's just "clicking on the white space", there must be something else see below ...
https://github.com/quarto-dev/quarto-cli/assets/8896044/c834be28-4e96-45b4-9a69-eba6c4404eb7

**Comment by zehuiyin** [comment]
I freshly installed Firefox can still produce the same issue. As I mentioned in the first comment, I believe it is related to the div element whose id is “quarto-sidebar-glass”.
![Recording 2024-01-06 at 13 17 49](https://github.com/quarto-dev/quarto-cli/assets/107876618/5a48edba-a7ec-468b-9703-d1654b770aec)

**Comment by mcanouil** [comment]
I see, it's about clicking on white space, it's about clicking on the following div on a fresh loading of the page.

```html
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item collapsed collapse" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-expanded="false" style=""></div>
```

It is clearly a JavaScript issue here and probably in how elements positions are computed.

**Comment by dragonstyle** [comment]
Fixed here:

https://github.com/quarto-dev/quarto-cli/commit/4a2da18c1d0f33871540cc705140b5f2957a7948

**Comment by zehuiyin** [comment]
I think this bug persists. I can still find this bug on the Quarto website's blog sections https://quarto.org/docs/blog/posts/2024-01-24-
![Recording 2024-02-04 at 16 21 26](https://github.com/quarto-dev/quarto-cli/assets/107876618/a28c0a4d-385b-46ec-9551-30c3924aca5b)
1.4-release/.
