### ISSUE TITLE
Uncaught error MissingEnvVarsError with .env.example file

### ISSUE THREAD

**Issue by adamalfredsson** [quarto-dev/quarto-cli#9262]
### Bug description

When serving a quarto notebook with an `.env.example` file present in the current working directory, there is an uncaught error from `dotenv`.

If this is not a bug, is there any way to disable this behaviour?

### Steps to reproduce

Add a `test.qmd` in an empty directory, with an `.env.example` file containing:

```
TEST_VAR=
```

Run `quarto render test.qmd`

### Expected behavior

Notebook should render

### Actual behavior

```bash
error: Uncaught (in promise) MissingEnvVarsError: The following variables were defined in the example file but are not present in the environment:
  TEST_VAR

Make sure to add them to your env file.

If you expect any of these variables to be empty, you can set the allowEmptyValues option to true.
        throw new MissingEnvVarsError(errorMessages.filter(Boolean).join("\n\n"), missingEnvVars);
              ^
    at assertSafe (file:///Applications/quarto/bin/quarto.js:26085:15)
    at load3 (file:///Applications/quarto/bin/quarto.js:26038:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.dotenv (file:///Applications/quarto/bin/quarto.js:26439:28)
    at async file:///Applications/quarto/bin/quarto.js:103001:23
```

### Your environment

MacOS

### Quarto check output

```bash
Quarto 1.4.537
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.537
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks for the report. I can confirm this happens and we need to fix this.

**Comment by cderv** [comment]
This should be fixed in current dev version, and will be included in next 1.5 pre-release. 

Thanks a lot for the report!

**Comment by mjpizz** [comment]
I'm still experiencing this in 1.5.57, is there a setting that I need to enable?

**Comment by cderv** [comment]
> I'm still experiencing this in 1.5.57, is there a setting that I need to enable?

The best way would be to open a new issue with what you try and what did not work. Unless the exact same example as above is not working for you.

**Comment by chriscarrollsmith** [comment]
I am getting this error in Quarto 1.6.43.

I have a .env file that contains the revelant variables. I even tried sourcing it before running the `quarto render` command. I also have a .env.example file, obviously. Both are in the directory I'm running the command from.

Tried a few different approaches to formatting the .env file, including removing special characters, removing comments, removing empty lines, quoting variables. None of these things fixed the issue.

Rolled back a few minor versions to 1.6.39 and still had the same issue.

Ironically, I don't think any of these variables are even used in the render.

Here's what _quarto.yml looks like:

```yaml
project:
  type: website
  output-dir: _docs

website:
  title: "FastAPI Webapp Template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/architecture.qmd
        text: Architecture
      - href: docs/authentication.qmd
        text: Authentication
      - href: docs/installation.qmd
        text: Installation
      - href: docs/customization.qmd
        text: Customization
      - href: docs/deployment.qmd
        text: Deployment
      - href: docs/contributing.qmd
        text: Contributing
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/fastapi-jinja2-postgres-webapp
  page-footer:
    left: "Copyright 2024, Promptly Technologies, LLC. MIT License."
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/fastapi-jinja2-postgres-webapp
format:
  html:
    theme: cosmo
    css: docs/static/styles.css
    toc: true
```

**Comment by mcanouil** [comment]
@chriscarrollsmith We kindly request that you avoid commenting on closed issues. Instead, please create a new issue, as noted in the preceding comment (https://github.com/quarto-dev/quarto-cli/issues/9262#issuecomment-2356719431). When doing so, ensure that all required information is included, such as a concise and reproducible example.
Posting incomplete code snippets is not helpful, as we are unable to utilise them effectively, and therefore, assistance cannot be provided.
